import { getCssText, globalCss, styled } from '~/stitches.config';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const globalStyles = globalCss({
  '*': {
    boxSizing: 'border-box',

    padding: 0,

    margin: 0,
  },
  'html, body': {
    backgroundColor: '$bgColor',
    color: '$textPrimary',
  },
  a: {
    color: 'inherit',
    textDecoration: 'none',
  },
  '@media (prefers-color-scheme: dark)': {
    html: {
      colorScheme: 'dark',
    },
  },
});

const Container = styled('div', {
  '&': {
    display: 'flex',
    flexDirection: 'column',

    minHeight: '100vh',
  },
});

const NoiseTexture = styled('svg', {
  position: 'fixed',
  top: 0,
  left: 0,
  width: '100%',
  height: '120vh',
  opacity: '0.2',
  zIndex: '$texture',
  pointerEvents: 'none',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  globalStyles();
  return (
    <html lang='en'>
      <head>
        <style dangerouslySetInnerHTML={{ __html: getCssText() }} />
      </head>
      <body>
        <NoiseTexture>
          <filter id='noise'>
            <feTurbulence
              type='fractalNoise'
              baseFrequency={0.9}
              numOctaves={4}
              stitchTiles='stitch'
            ></feTurbulence>
            <feColorMatrix type='saturate' values='0'></feColorMatrix>
          </filter>
          <rect width='100%' height='100%' filter='url(#noise)'></rect>
        </NoiseTexture>
        <Container>{children}</Container>
      </body>
    </html>
  );
}
